### ISSUE TITLE
530 TLS subsystem failed. Check syslog for details...

### ISSUE THREAD

**Issue by splifter** [jonathanbower/docker-glftpd#1]
When starting the container and after the first user setup, the connection won't be established due to following error:
FTP Client message:
> 530 TLS subsystem failed. Check syslog for details...
Syslog:
> Dec 29 10:52:43 1k6z47abd43c glftpd: 111.111.111.11: connected: DHPARAM certificate file not found!

Generating the DHPARAM via openssl fixes this:
openssl dhparam -out /glftpt/ftpd-dhparam.pem -2 1024

Could you implement the generation automatically so i doesn't need manual intervention?

**Comment by jonathanbower** [comment]
It should work if you comment out DHPARAM_FILE from the glftpd.conf file.
I've implemented this in a53532f3d9d09cc1d44be823544c12c43441d930 , does this work for you?

**Comment by splifter** [comment]
Thank you. Tried to comment it out and had some issues with it. Now it work fine. Thank you!

One unrelated question though. rar/ unrar is not installed. how do you handle this or is it not needed for you? i logged into the container and tried to install it but it didn't work.
Because i get following error with the zupscript:

> [14:50:50] [R] 226- -e Testing file ubuntu-19.10-desktop-amd64.rar
> [14:50:50] [R] 226- /bin/zipscript: 55: /bin/zipscript: /bin/unrar: not found
> [14:50:50] [R] 226- -e /bin/unrar failed!
> [14:50:50] [R] 226- Error: post_check script (zipscript) could not be executed, file not tested.

**Comment by jonathanbower** [comment]
Did you put unrar in /glftpd/bin ? I use /bin/zipscript-c from https://github.com/jonathanbower/docker-glftpd#pz-ng , unrar should not be needed.

**Comment by jonathanbower** [comment]
I added unrar 1527e0119486aa0e65fa716b5ad9824f6e6d16f9 if you wish to use /bin/zipscript

**Comment by splifter** [comment]
Thank you!
