### ISSUE TITLE
runsv cron: fatal: unable to start ./run: access denied

### ISSUE THREAD

**Issue by aZRGaOmjIw** [jonathanbower/docker-glftpd#12]
I use your docker on a synology NAS. When i connect to the terminal glftpd i see this message:

runsv cron: fatal: unable to start ./run: access denied

glftpd seems to work fine , any idea what this message is ?

**Comment by aZRGaOmjIw** [comment]
Its not synology related. On a simple docker linux host i see the same issue. When i delete /etc/service/cron and i kill the proces the error is gone. Hope you find a solution

**Comment by jonathanbower** [comment]
Hey there. Give it a try now.

**Comment by aZRGaOmjIw** [comment]
Looks good! Many thanks!
