### ISSUE TITLE
Remote connection denied - only able to connect via localhost/127.0.0.1

### ISSUE THREAD

**Issue by kreditor0815** [jonathanbower/docker-glftpd#2]
Hi there,

i just used docker run to install your glftpd container from the docker hub. I just added a user according to your instrcutions from README.md which worked perfectly fine but im unable to connect to the glftpd from a remote machine. Can u help me make it work?

**Comment by jonathanbower** [comment]
Have a look at the "site addip" command in https://glftpd.io/latest/docs/glftpd.docs . For further help you can try the IRC channel #glhelp on EFNet

**Comment by jonathanbower** [comment]
closed
