### ISSUE TITLE
runit issue

### ISSUE THREAD

**Issue by estimadarocha** [jonathanbower/docker-glftpd#3]
docker logs glftpd
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
No SSH host key available. Generating one...
Creating SSH2 RSA key; this may take some time ...
2048 SHA256:otgpWSoutCurruDUaQ48H9I8iMMcyE3hH2EdsGv0e9Q root@9b0f1a232b29 (RSA)
Creating SSH2 ECDSA key; this may take some time ...
256 SHA256:pyeQx93vmVfhIM+oA4Wis/nBTveVGho2nQyjFZGcjBU root@9b0f1a232b29 (ECDSA)
Creating SSH2 ED25519 key; this may take some time ...
256 SHA256:bdGhjMCMNRlVFaMH4A+twP9z1L5dtgTftl2PDEvrG2g root@9b0f1a232b29 (ED25519)
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of restart.
*** Running /etc/my_init.d/10_syslog-ng.init...
Mar 31 13:50:57 9b0f1a232b29 syslog-ng[148]: syslog-ng starting up; version='3.13.2'
*** Booting runit daemon...
*** Runit started as PID 155
runsv boot: warning: unable to open supervise/pid.new: file does not exist
 * Starting internet superserver xinetd
   ...done.
Mar 31 13:50:58 9b0f1a232b29 xinetd[175]: 2.3.15.3 started with libwrap loadavg labeled-networking options compiled in.
Mar 31 13:50:58 9b0f1a232b29 xinetd[175]: Started working: 1 available service
runsv boot: warning: unable to open supervise/pid.new: file does not exist
runsv boot: warning: unable to open supervise/pid.new: file does not exist
runsv boot: warning: unable to open supervise/pid.new: file does not exist
runsv boot: warning: unable to open supervise/pid.new: file does not exist

**Comment by jonathanbower** [comment]
59dcf30216ad2aee0e164c116ec0ae9368ba1ab5 should fix this. thanks.
