### ISSUE TITLE
Cannot add *@* as suggested in docker howto

### ISSUE THREAD

**Issue by PeeBeerBeach** [jonathanbower/docker-glftpd#4]
When i add an IP in the format "site addip user *@*" like suggest in the docker howto  of jonarin/glftpd I get an error:
"IP not added: it is not specific enough."

So it is not possible to connect from any IP. 
How to get around this?

**Comment by jonathanbower** [comment]
Instead of *@* you can use username@127.0.0.1 to be more specific. If you don't want to have ip rules you can just comment out the secure_ip line and use *@*

**Comment by PeeBeerBeach** [comment]
Thanks!
