### ISSUE TITLE
Bind failed (Adress already in use)

### ISSUE THREAD

**Issue by PeeBeerBeach** [jonathanbower/docker-glftpd#5]
I have configure my GLFTPD instance using your docker and it worked fine for a while. Now i restarted the docker after a few days i am runniny into a bind issue:

`May 23 18:15:52 debNAS xinetd[108]: bind failed (Address already in use (errno = 98)). service = glftpd
May 23 18:15:52 debNAS xinetd[108]: Service glftpd failed to start and is deactivated.`

I tried changing the ports and also removed and reinstalled the docker. No matter what port i chose i get this same error, so it has to be related to something different.
I am not sure if the issue is caused by the docker,, but assume so.
I could not find any duplicate ports by "netstat -tuan"

Any idea?

**Comment by PeeBeerBeach** [comment]
I have just deleted the whole ftp-data folder and now the  issue is gone.  No iidea what it was but seems to be connected to any file in there. possibly misconfig.

**Comment by jonathanbower** [comment]
I don't think this error message can be caused by anything in the configuration files. I'ts probably unrelated to your problem.

**Comment by jonathanbower** [comment]
Unrelated issue
