### ISSUE TITLE
please add support for psxc-imdb script 

### ISSUE THREAD

**Issue by LilM21** [jonathanbower/docker-glftpd#8]
glftpd\ftp-data\pzs-ng-master\scripts\psxc-imdb\

thx a lot

**Comment by jonathanbower** [comment]
Check the latest commit if it works for you. script has been installed without configuration.

**Comment by jonathanbower** [comment]
fixed

**Comment by LilM21** [comment]
I dont know whats wrong but i don't get any data, btw lynx was required and it was not included in the docker. I guess you have not tested psxc at all.  I guess it could be a permission problem.
